study:
    resource: "@StudyBundle/Resources/config/routing.yml"
    prefix:   /study

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin
api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /app
